# Generated by Django 4.2.5 on 2023-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registermodel_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registermodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
