# Generated by Django 4.2.5 on 2023-09-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_registermodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='staff',
        ),
    ]
