# Generated by Django 4.2.5 on 2023-09-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registermodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='admin',
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
