# Generated by Django 4.2.5 on 2023-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_registermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
