# Generated by Django 4.2.5 on 2023-09-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_registermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
